package com.dnd.dndTable.creatingDndObject.bagDnd;

import com.fasterxml.jackson.annotation.JsonTypeName;

@JsonTypeName("TOOL")
public class Tool extends Items
{
	private static final long serialVersionUID = 1L;


	public Tool() {}
	
	public Tool(Tools type)
	{
		this.setDescription(type.text);
		this.setName(type.name);
	}

	public enum Tools
	{
		SMITH("Smith’s Tools", "Inside:\r\n"
				+ "• hammers,\r\n"
				+ "• pincers,\r\n"
				+ "• coal,\r\n"
				+ "• rags,\r\n"
				+ "• grindstone.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "MAGIC and HISTORY.\r\n"
				+ "Your experience gives you additional knowledge when examining metal objects such as weapons.\r\n"
				+ "\r\n"
				+ "RESEARCH.\r\n"
				+ "You may discover clues that others may not see when the investigation is about armor, weapons, or other pieces of metalwork.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Repair. With access to tools and an open fire that is hot enough to ductile metal, you can repair 10 hit points of a damaged metal object for every hour of work.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Sharpen a dull blade\r\n"
				+ "15 Repair a set of armor\r\n"
				+ "15 Dismantle non-magical metal object"),
		NAVIGATOR("Navigator’s Tools", "Inside:\r\n"
				+ "• sextant,\r\n"
				+ "• compass,\r\n"
				+ "• caliper,\r\n"
				+ "• ruler,\r\n"
				+ "• parchment,\r\n"
				+ "• ink,\r\n"
				+ "• writing pen.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "SURVIVAL. Knowing how to use navigation tools helps you avoid getting lost and gives you knowledge of the most likely location of roads and settlements.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Position definition. With careful measurements, you can determine your position on the nautical chart and the time of day.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Plot a course\r\n"
				+ "15 Determine your position on the marine navigation chart"),
		THIEVES("Thieves’ Tools", "Inside:\r\n"
				+ "• a small file,\r\n"
				+ "• a set of master keys,\r\n"
				+ "• a small mirror with a long handle,\r\n"
				+ "• a set of scissors with narrow blades,\r\n"
				+ "• a pair of tweezers.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "HISTORY.\r\n"
				+ "Your knowledge of traps gives you additional knowledge when answering questions about places famous for their traps.\r\n"
				+ "RESEARCH and PERCEPTION.\r\n"
				+ "You gain additional knowledge when looking for traps, because you know various simple signs that give away their presence.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Setting up a trap.\r\n"
				+ "You can not only disable traps, but also set them. As part of a short rest, you can create a trap from improvised means. The result of your check becomes a challenge for anyone trying to detect or disable the trap. The trap deals damage equal to the materials used in its creation (such as poison or weapons), or damage equal to half the result of your check, whichever the DM deems more appropriate.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "Various Open the lock\r\n"
				+ "Disarm the trap"),
		DRAGON_CHESS("Dragon Chess", "Inside:\r\n"
				+ "A game set includes everything needed for a particular game or group of games, such as a full deck of cards or a board and pieces.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "HISTORY.\r\n"
				+ "Your mastery of the game includes knowledge of its history, as well as knowledge of important events and famous historical figures associated with the game.\r\n"
				+ "INSIGHT.\r\n"
				+ "Playing with someone is a great way to understand their personality and what they are, which in turn allows you to better recognize lies and determine their mood.\r\n"
				+ "SLEIGHT OF HAND.\r\n"
				+ "Sleight of Hand is a useful skill for cheating in the game, as it allows you to swap pieces, hide cards, or reverse a bad die roll. On the other hand, captivating the target with a game that requires dexterous movements is a good distraction for pickpocketing.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Catch a player on a cheat\r\n"
				+ "15 Understand the character of the opponent"),
		ALCHEMIST("Alchemist’s Supplies","Inside:\r\n"
				+ "• two glass beakers,\r\n"
				+ "• a metal frame that holds the beaker above an open flame,\r\n"
				+ "• glass stick for stirring,\r\n"
				+ "• small mortar\r\n"
				+ "• pestle,\r\n"
				+ "• a pouch of common alchemy ingredients, including\r\n"
				+ "     ◦ salt\r\n"
				+ "     ◦ crushed iron,\r\n"
				+ "     ◦ distilled water.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "Proficiency with alchemist's tools allows you to reveal more information on Magic checks involving potions and similar substances.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When you search an area for clues, wielding an alchemist's tools grants additional knowledge about what chemicals and other substances were used in the area.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Alchemical craft.\r\n"
				+ "You can use tool proficiency to craft alchemical items. The character can spend money to gather raw materials, which weigh 1 pound for every 50 gp used. The GM may allow the character to pass the Identification check with advantage.\r\n"
				+ "As part of a long rest, you can use the alchemist's tools to make one serving of\r\n"
				+ "• acids,\r\n"
				+ "• alchemical fire,\r\n"
				+ "• antidotes,\r\n"
				+ "• oils,\r\n"
				+ "• spirits\r\n"
				+ "• soap.\r\n"
				+ "Subtract half the cost of the crafted item from the total cost of the raw materials you collected.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Create puffs of thick smoke\r\n"
				+ "10 Identify Poison\r\n"
				+ "15 Identify the substance\r\n"
				+ "15 Arson\r\n"
				+ "20 Neutralize Acid"),
		POTTER("Potter’s Tools","Inside:\r\n"
				+ "• pottery needles,\r\n"
				+ "• cycles,\r\n"
				+ "• scrapers,\r\n"
				+ "• knife,\r\n"
				+ "• caliper.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your knowledge and experience helps you to identify ceramic objects by knowing when they were made and from which places or cultures they come.\r\n"
				+ "\r\n"
				+ "Investigation, Perception.\r\n"
				+ "You gain additional knowledge when examining ceramics, finding clues that others may not notice on small bumps and chips.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Restoration of appearance.\r\n"
				+ "After examining ceramic shards, you can determine the origin of the object, its original shape and possible purpose.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Determine what was in the vessel\r\n"
				+ "15 Create a durable pot\r\n"
				+ "20 Find the weak point of a ceramic object"),
		CALIGRAF("Calligrapher’s Supplies","Inside:\r\n"
				+ "• ink,\r\n"
				+ "• a lot of parchment sheets,\r\n"
				+ "• three writing pens.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "While calligraphy is of little help in deciphering the contents of a magical text, mastery of these tools helps determine who wrote the magical text.\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Proficiency with these tools can increase the benefit of a successful check made to analyze or examine ancient writings, scrolls, or other text, including runes carved into stone, and inscriptions in frescoes or other images.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Treasure map decryption.\r\n"
				+ "Mastery of these tools allows you to conduct an examination of maps. You can make an Intelligence check to estimate the age of the card, determine if the card contains a hidden message, and so on.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Identify the writer of the non-magical handwriting\r\n"
				+ "15 Determine the state of mind of the writer\r\n"
				+ "15 Recognize fake text\r\n"
				+ "20 Forge a signature"),
		MASON("Mason’s Tools","Inside:\r\n"
				+ "• Master OK,\r\n"
				+ "• hammer,\r\n"
				+ "• chisel,\r\n"
				+ "• brushes,\r\n"
				+ "• square.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your experience helps you determine the date and purpose of a stone building, and who might have built it.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "You gain additional knowledge when examining rooms in a stone building.\r\n"
				+ "\r\n"
				+ "Perception.\r\n"
				+ "You notice irregularities in the stone walls and floors, making it easier to find traps and secret passages.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Demolition.\r\n"
				+ "Your knowledge of stone architecture allows you to find vulnerabilities in the masonry of stone walls. You deal double damage to such structures with your weapon attacks.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Punch a small hole in the stone wall with a chisel\r\n"
				+ "15 Find a weak spot in the stone wall"),
		CARTOGRAPH("Cartographer’s Tools","Inside:\r\n"
				+ "• writing pen,\r\n"
				+ "• ink,\r\n"
				+ "• parchment,\r\n"
				+ "• compass,\r\n"
				+ "• caliper,\r\n"
				+ "• ruler.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History, Religion.\r\n"
				+ "You can use your knowledge of maps and locations to extract more detailed information when using these skills. For example, you can find a hidden message on a map, find out when the map was made to determine what geographic features have changed since then, and so on.\r\n"
				+ "\r\n"
				+ "Nature.\r\n"
				+ "Your familiarity with physical geography makes it easier for you to find answers to questions and problems about your surroundings.\r\n"
				+ "\r\n"
				+ "Survival.\r\n"
				+ "Your understanding of geography makes it easier to find your way to civilization, allows you to predict where villages or towns may be found, and reduces the chance of you getting lost. You have studied so many maps that general trends, such as how trade routes develop or where settlements are usually built, are familiar to you.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Making a map.\r\n"
				+ "While traveling, you can draw a map in addition to participating in other activities.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Determine the age and origin of the map\r\n"
				+ "15 Estimate the direction and distance to the landmark\r\n"
				+ "15 Recognize that the card is fake\r\n"
				+ "20 Draw the missing piece of the map"),
		LEATHERWORK("Leatherworker’s Tools", "Inside:\r\n"
				+ "• leather cutter (knife),\r\n"
				+ "• a small mallet,\r\n"
				+ "• groove cutter,\r\n"
				+ "• punch,\r\n"
				+ "• a thread,\r\n"
				+ "• pieces of skin.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "Your knowledge and experience with leather gives you additional knowledge when examining magical items made from leather, such as boots or some cloaks.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "You gain additional knowledge when you examine leather items or clues related to them, and you use your knowledge of leatherworking to find clues that others may not notice.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Skin identification.\r\n"
				+ "By looking at a piece of leather or a leather object, you can determine the source of the leather and any special techniques used in processing it. For example, you can tell the difference between leather crafted using dwarven techniques and leather crafted using halfling techniques.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Change the appearance of a leather item\r\n"
				+ "20 Determine the past of a leather item"),
		POISONER("Poisoner’s Kit","Inside:\r\n"
				+ "• glass bottles,\r\n"
				+ "• mortar\r\n"
				+ "• pestle,\r\n"
				+ "• chemical reagents,\r\n"
				+ "• glass stick for stirring.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your training in the use of poisons can help you when trying to remember facts about infamous poisonings.\r\n"
				+ "\r\n"
				+ "Investigation, Perception.\r\n"
				+ "Your knowledge of poisons has taught you to be careful when dealing with these substances, thus aiding you when examining a poisoned item or getting leads on poison related events.\r\n"
				+ "\r\n"
				+ "The medicine.\r\n"
				+ "When you treat a victim of poison, your awareness can give you additional knowledge on how to properly care for the poisoned.\r\n"
				+ "\r\n"
				+ "Nature, Survival.\r\n"
				+ "Working with poisons allowed you to gain knowledge about which plants and animals are poisonous.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Handling poisons.\r\n"
				+ "Your proficiency allows you to carefully handle poisons and use them without risking exposure to them yourself.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Identify the poisoned object\r\n"
				+ "20 Determine Poison Effect"),
		BREWER("Brewer’s Supplies","Inside:\r\n"
				+ "• a large glass bottle,\r\n"
				+ "• some hops,\r\n"
				+ "• siphon,\r\n"
				+ "• coil,\r\n"
				+ "• several feet of tubing.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Proficiency with a brewer's tools gives you additional knowledge on Intelligence (History) checks regarding events in which alcohol was an important part.\r\n"
				+ "\r\n"
				+ "The medicine.\r\n"
				+ "Mastery of these tools provides additional knowledge when you alleviate alcohol poisoning, hangovers, or when using alcohol to dull pain.\r\n"
				+ "\r\n"
				+ "Belief.\r\n"
				+ "A strong drink can help soften even a stone heart. Your mastery of the brewer's tools can help you give someone just the right amount of alcohol to cheer them up.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Distillation.\r\n"
				+ "Your knowledge of brewing allows you to purify water that would otherwise be undrinkable. You can clear up to 6 gallons of water as part of a long rest, or 1 gallon as part of a short rest.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Detect poison or impurity in drink\r\n"
				+ "15 Identify alcohol\r\n"
				+ "20 Ignore the effect of alcohol"),
		CARPENTER("Carpenter’s Tools","Inside:\r\n"
				+ "• saw,\r\n"
				+ "• hammer,\r\n"
				+ "• nails,\r\n"
				+ "• axe,\r\n"
				+ "• square,\r\n"
				+ "• ruler,\r\n"
				+ "• encoder,\r\n"
				+ "• planer,\r\n"
				+ "• chisel.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "You gain additional knowledge when exploring an area in a wooden building because you know building tricks that can hide something in an area when you explore.\r\n"
				+ "\r\n"
				+ "Perception.\r\n"
				+ "You may notice bumps in the wooden walls and floors, making it easier to find traps and secret passages.\r\n"
				+ "\r\n"
				+ "Stealth.\r\n"
				+ "You can quickly find a weak spot in a hardwood floor, making it easier for you to spot areas that will break or squeak if stepped on.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Strengthening.\r\n"
				+ "In 1 minute, if you have materials, you can strengthen the door or window. The knockout roll's DC is increased by 5.\r\n"
				+ "\r\n"
				+ "Temporary shelter.\r\n"
				+ "As part of a long rest, you can build a canopy or similar shelter to keep your group out of the rain or the sun during the rest. Because it was built in haste from the first available timber, the shelter falls apart 1d3 days after construction.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Build a simple wooden structure\r\n"
				+ "15 Design a complex wooden structure\r\n"
				+ "15 Find a weak spot in a wooden wall\r\n"
				+ "20 Remove door from hinges"),
		COOK("Cook’s Utensils","Inside:\r\n"
				+ "• knife,\r\n"
				+ "• chisel,\r\n"
				+ "• small saw.\r\n\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your knowledge of culinary techniques allows you to evaluate the structure of social development based on the gastronomic customs of this culture.\r\n"
				+ "\r\n"
				+ "The medicine.\r\n"
				+ "By providing healing, you can turn bitter or sour medicine into a palatable concoction.\r\n"
				+ "\r\n"
				+ "Survival.\r\n"
				+ "By obtaining food, you can use the ingredients you have collected that others could not cook.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Cooking.\r\n"
				+ "As part of a short break, you can prepare a delicious meal to help your companions recuperate. You and up to five creatures of your choice regain 1 extra hit point for each Hit Dice spent during a short rest, provided you have access to your cook's tools and enough food.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Cook regular food\r\n"
				+ "10 Repeat a dish10Detect a poison or impurity in food\r\n"
				+ "15 Detect poison or impurities in food\r\n"
				+ "15 Cook a gourmet meal"),
		WOOD("Woodcarver’s Tools","Inside:\r\n"
				+ "• knife,\r\n"
				+ "• chisel,\r\n"
				+ "• small saw.\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History.\r\n"
				+ "Your experience gives you additional knowledge when examining wooden objects such as figurines or arrows.\r\n"
				+ "\r\n"
				+ "Nature.\r\n"
				+ "Your knowledge of wood gives you additional knowledge when you study trees.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Repair.\r\n"
				+ "As part of a short rest, you can repair one damaged piece of wood.\r\n"
				+ "\r\n"
				+ "Make arrows.\r\n"
				+ "As part of a short rest, you can make up to five arrows. As part of a long rest, you can do up to twelve. You must have wood on hand to make arrows.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Make a small wooden figurine\r\n"
				+ "10 Carve an intricate pattern on wood"),
		TINKER("Tinker’s Tools","Vnutri: • razlichnyye ruchnyye instrumenty, • nitki, • igolki, • tochil'nyy kamen', • kuski tkani i kozhi, • nebol'shuyu banku kleya (sinyuyu izolentu poka, uvy, ne pridumali). Kogda vy delayete proverku SKILOV vy mozhete poluchit' preimushchestva: Istoriya.  Vy mozhete opredelit' vozrast i proiskhozhdeniye predmeta, dazhe yesli u vas v nalichii vsego neskol'ko oskolkov, ostavshikhsya ot originala. Rassledovaniye.  Kogda Vy osmatrivayete povrezhdonnyy predmet, Vy uznayote, kak i naskol'ko davno on byl povrezhdon. A takzhe vy mozhet: Pochinka.  Vy mozhete vosstanovit' po 10 khitov povrezhdonnogo predmeta za kazhdyy chas raboty. Dlya pochinki lyubogo predmeta vam neobkhodim dostup k materialam, neobkhodimym dlya remonta. Dlya metallicheskikh predmetov vam nuzhen dostup k otkrytomu ognyu, zhara kotorogo dostatochno, chtoby sdelat' metall plastichnym. Dopolnitel'nyye vozmozhnosti po rezul'tatam broska: 10 Vremenno pochinit' povrezhdonnyy mekhanizm 15 Pochinit' predmet vdvoye bystreye 20 Smasterit' iz khlama vremennyy predmet\r\n"
				+ "Ещё\r\n"
				+ "979 / 5 000\r\n"
				+ "Результаты перевода\r\n"
				+ "Перевод\r\n"
				+ "Inside:\r\n"
				+ "• various hand tools,\r\n"
				+ "• threads,\r\n"
				+ "• needles,\r\n"
				+ "• grindstone,\r\n"
				+ "• pieces of cloth and leather,\r\n"
				+ "• a small jar of glue (blue duct tape, alas, has not yet been invented).\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "You can determine the age and origin of an item, even if you only have a few fragments left from the original.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When you inspect a damaged item, you will find out how and how long ago it was damaged.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Repair.\r\n"
				+ "You can restore 10 hit points of a damaged item for each hour of work. To repair any item, you need access to the materials needed for the repair. For metal objects, you need access to an open fire that is hot enough to make the metal malleable.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Temporarily repair the damaged mechanism\r\n"
				+ "15 Repair an item twice as fast\r\n"
				+ "20 Craft a temporary item out of junk"),
		COBBLER("Cobbler’s Tools","Inside:\r\n"
				+ "• hammer,\r\n"
				+ "• awl,\r\n"
				+ "• knife,\r\n"
				+ "• shoe last,\r\n"
				+ "• scissors,\r\n"
				+ "• stock of leather,\r\n"
				+ "• stock of threads.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History.\r\n"
				+ "Your knowledge of shoes helps you determine the magical properties of enchanted boots or learn the history of such items.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "Shoes hide many secrets. You can find out where the person whose shoes you are inspecting for dirt and wear was recently. Your experience in repairing shoes makes it easier for you to determine how the shoe was damaged.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Shoe care.\r\n"
				+ "As part of a long rest, you can repair your companions' shoes. For the next 24 hours, up to 6 creatures of your choice wearing the shoes you've worked on can travel up to 10 hours per day without passing exhaustion tests.\r\n"
				+ "\r\n"
				+ "Creation of a secret compartment.\r\n"
				+ "For 8 hours of work, you can add a secret compartment to a pair of shoes. The compartment can hold an object up to 3 inches long and 1 inch wide and high. You make an Intelligence check, adding your proficiency bonus for these tools, to determine the DC of the Intelligence (Investigation) check required to locate the squad.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Determine the age and origin of shoes\r\n"
				+ "15 Find the secret compartment in the heel"),
		GLASS("Glassblower’s Tools","You need a heat source to work with glass.\r\n"
				+ "\r\n"
				+ "Inside:\r\n"
				+ "• blowing tube,\r\n"
				+ "• a small glass-blowing run-in,\r\n"
				+ "• katalnik,\r\n"
				+ "• development\r\n"
				+ "• tongs.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History.\r\n"
				+ "Your knowledge of glassblowing techniques will help you when you study a glass object, such as a potion bottle or a glass object found in treasure. For example, you can study how a glass potion flask is affected by its contents to help determine the effect of the potion. (The potion may leave a residue, warp the glass, or stain it.)\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When you are exploring an area, your knowledge can help you if the evidence includes broken glass or glass objects.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Identification of a weak spot.\r\n"
				+ "After spending 1 minute, you can find the weak point of the glass object. Any damage dealt to an item when attacking a weak spot is doubled.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Determine the origin of the glass\r\n"
				+ "20 Determine what a glass object once contained"),
		WEAWER("Weaver’s Tools","Inside:\r\n"
				+ "• threads,\r\n"
				+ "• needles\r\n"
				+ "• pieces of cloth.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History.\r\n"
				+ "Your experience gives you additional knowledge when inspecting wardrobe items, including cloaks and other capes.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "By using your knowledge of the tailoring process, when examining tapestries, upholstery, garments, and other woven items, you can find clues that others may not notice.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Repair.\r\n"
				+ "As part of a short rest, you can repair one damaged piece of clothing.\r\n"
				+ "Tailoring.\r\n"
				+ "As part of a long rest, you can create clothing for the creature, provided you have enough fabric and thread.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Fabric reuse\r\n"
				+ "10 Fabric reuse\r\n"
				+ "15 Hem the outfit"),
		PAINT("Painter’s Supplies","Inside:\r\n"
				+ "• easel,\r\n"
				+ "• canvas,\r\n"
				+ "• paints,\r\n"
				+ "• brushes,\r\n"
				+ "• charcoal pencils,\r\n"
				+ "• palette.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic, History, Religion.\r\n"
				+ "Your experience helps you uncover any kind of knowledge that is associated with works of art, such as the magical properties of a painting or the origin of a strange fresco found in a dungeon.\r\n"
				+ "\r\n"
				+ "Investigation, Perception.\r\n"
				+ "When you look at a painting or similar work of fine art, your awareness of how it was created can give you additional knowledge.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "\r\n"
				+ "Writing and drawing.\r\n"
				+ "As part of a short or long stay, you can create a simple piece of art. While your creation may not be accurate enough, you can capture an image or scene, or make a quick copy of an artwork you've seen.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Write an accurate portrait\r\n"
				+ "20 Create a painting with a hidden message"),
		JEWELER("Jeweler’s Tools","Inside:\r\n"
				+ "• small saw\r\n"
				+ "• hammer,\r\n"
				+ "• files,\r\n"
				+ "• tongs,\r\n"
				+ "• tweezers.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "Proficiency with jeweler's tools gives you knowledge of known magical uses for gemstones. This knowledge will come in handy on Magic checks involving gems or gem-encrusted items.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When examining jewelry, mastering a jeweler's tools helps you find clues that others would overlook.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Jewel identification.\r\n"
				+ "You can identify the jewel and determine its value by eye.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Change the appearance of a jewel\r\n"
				+ "20 Identify past jewels"),
		CARDS("Playing Card Set","Inside:\r\n"
				+ "A game set includes everything needed for a particular game or group of games, such as a full deck of cards or a board and pieces.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your mastery of the game includes knowledge of its history, as well as knowledge of important events and famous historical figures associated with the game.\r\n"
				+ "\r\n"
				+ "Insight.\r\n"
				+ "Playing with someone is a great way to understand their personality and what they are, which in turn allows you to better recognize lies and determine their mood.\r\n"
				+ "\r\n"
				+ "Sleight of hand.\r\n"
				+ "Sleight of Hand is a useful skill for cheating in the game, as it allows you to swap pieces, hide cards, or reverse a bad die roll. On the other hand, captivating the target with a game that requires dexterous movements is a good distraction for pickpocketing.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Catch a player on a cheat\r\n"
				+ "15 Understand the character of the opponent"),
		DICE("Dice Set","Inside:\r\n"
				+ "A game set includes everything needed for a particular game or group of games, such as a full deck of cards or a board and pieces.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your mastery of the game includes knowledge of its history, as well as knowledge of important events and famous historical figures associated with the game.\r\n"
				+ "\r\n"
				+ "Insight.\r\n"
				+ "Playing with someone is a great way to understand their personality and what they are, which in turn allows you to better recognize lies and determine their mood.\r\n"
				+ "\r\n"
				+ "Sleight of hand.\r\n"
				+ "Sleight of Hand is a useful skill for cheating in the game, as it allows you to swap pieces, hide cards, or reverse a bad die roll. On the other hand, captivating the target with a game that requires dexterous movements is a good distraction for pickpocketing.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Catch a player on a cheat\r\n"
				+ "15 Understand the character of the opponent"),
		DISGUISE("Disguise Kit","Inside:\r\n"
				+ "• various cosmetics,\r\n"
				+ "• hair dye,\r\n"
				+ "• some props,\r\n"
				+ "• several outfits.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Deception.\r\n"
				+ "In some cases, makeup can help you spin more convincing lies.\r\n"
				+ "\r\n"
				+ "Intimidation.\r\n"
				+ "The right image can make you more intimidating when you want to scare someone away by pretending to be infected with the plague, or when you intimidate a gang of bandits under the guise of a thug-thug.\r\n"
				+ "\r\n"
				+ "Performance.\r\n"
				+ "The art of disguise can increase audience satisfaction with a performance, provided the guise is properly designed to evoke the desired reaction.\r\n"
				+ "\r\n"
				+ "Belief.\r\n"
				+ "People tend to trust people in uniform. If you disguise yourself as an authority figure, your attempts to convince others are usually more effective.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Form creation.\r\n"
				+ "As part of a long rest, you can create a disguise. It takes 1 minute to put on the skin after it is created. You can only have one of these skins on you at a time without drawing undue attention, unless you have a Bag of holding or some other similar way to keep them undetected. Each such guise weighs 1 pound.\r\n"
				+ "In other cases, it takes 10 minutes to create a skin that slightly changes your appearance, and 30 minutes if more extensive changes are required.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "10 Hide injuries or special features\r\n"
				+ "15 Recognize someone else's use of disguises\r\n"
				+ "20 Copy humanoid appearance"),
		THREE_DRAGON("Three-Dragon Ante", "Inside:\r\n"
				+ "Components. A game set includes everything needed for a particular game or group of games, such as a full deck of cards or a board and pieces.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "Your mastery of the game includes knowledge of its history, as well as knowledge of important events and famous historical figures associated with the game.\r\n"
				+ "\r\n"
				+ "Insight.\r\n"
				+ "Playing with someone is a great way to understand their personality and what they are, which in turn allows you to better recognize lies and determine their mood.\r\n"
				+ "\r\n"
				+ "Sleight of hand.\r\n"
				+ "Sleight of Hand is a useful skill for cheating in the game, as it allows you to swap pieces, hide cards, or reverse a bad die roll. On the other hand, captivating the target with a game that requires dexterous movements is a good distraction for pickpocketing.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Catch a player on a cheat\r\n"
				+ "15 Understand the character of the opponent"),
		HERBAlISM("Herbalism Kit","Inside:\r\n"
				+ "• bags for storing herbs,\r\n"
				+ "• secateurs,\r\n"
				+ "• leather gloves for collecting plants,\r\n"
				+ "• several glass jars,\r\n"
				+ "• mortar,\r\n"
				+ "• pestle.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "Your familiarity with the nature and use of plants can give you additional knowledge of magical research when it comes to plants and trying to identify a potion.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When you're exploring a planted area, owning this set helps you find details and clues that others might overlook.\r\n"
				+ "\r\n"
				+ "The medicine.\r\n"
				+ "Your skill as an herbalist enhances your ability to heal diseases and wounds, expanding the methods available through the use of medicinal plants.\r\n"
				+ "\r\n"
				+ "Nature and Survival.\r\n"
				+ "When you travel in the wilderness, your herbalism skills make it easier to identify plants and find food sources that others may not notice.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Plant identification. You can quickly recognize most plants by smell and appearance.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Find plants\r\n"
				+ "20 Identify Poison"),
		FROGERY("Forgery Kit","Inside:\r\n"
				+ "• a small file,\r\n"
				+ "• a set of master keys,\r\n"
				+ "• a small mirror with a long handle,\r\n"
				+ "• a set of scissors with narrow blades,\r\n"
				+ "• a pair of tweezers.\r\n"
				+ "\r\n"
				+ "When you make a SKILL check you can gain the following benefits:\r\n"
				+ "\r\n"
				+ "Magic.\r\n"
				+ "The Forgery Kit can be used in conjunction with the Magic skill to determine if a magic item is real or fake.\r\n"
				+ "\r\n"
				+ "Deception.\r\n"
				+ "A well-executed forgery, such as a document certifying your nobility or a warrant guaranteeing you safe passage, can lend credibility to your lies.\r\n"
				+ "\r\n"
				+ "History.\r\n"
				+ "The Forgery Kit, along with your knowledge of history, improves your ability to forge historical documents or determine their authenticity.\r\n"
				+ "\r\n"
				+ "Investigation.\r\n"
				+ "When you inspect an item, owning a forgery kit helps determine how the item was made and whether it is genuine.\r\n"
				+ "\r\n"
				+ "And also you can:\r\n"
				+ "Other tools. Knowing how to use other tools makes your forgeries more believable. For example, you can combine ownership of a falsification kit and ownership of cartographer's tools to make a fake map.\r\n"
				+ "Quick fake. As part of a short break, you can create a fake document no longer than one page. As part of a long break, you can create a document up to four pages long. Your Intelligence check in using a fake kit determines the strength of your Intelligence (Investigation) check to determine if it's a fake.\r\n"
				+ "\r\n"
				+ "Additional abilities based on roll results:\r\n"
				+ "15 Fake Underline\r\n"
				+ "20 Copy Wax Seal");






		Tools(String name, String text)
		{
			this.name = name;
			this.text = text;
		}
		private String text;
		private String name;

		public String toString()
		{
			return name;
		}

	}
}
